version: '3'
services:
  pgsql:
    image: 'postgres:latest'
    ports:
        - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
        POSTGRES_DB: ${DB_DATABASE}
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
        - ./db_data:/var/lib/pgsql
    networks:
        - sail

networks:
  sail:
    driver: bridge
